### ISSUE TITLE
Build Quarkus Backend as Native Image

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#106]
***In GitLab by @xit-paul-reinhardt on Aug 1, 2024, 09:31 GMT+2:***

Right now the Quarkus-based backend is built as a jar to run on JVM. This was changed from using a nativ executable in this MR: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/139

The reason for this was the following error when starting the native executable:

`Exception in thread "main" java.lang.ExceptionInInitializerError at java.base@17.0.12/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) at java.base@17.0.12/java.lang.reflect.Constructor.newInstance(Constructor.java:481) at io.quarkus.runtime.Quarkus.run(Quarkus.java:70) at io.quarkus.runtime.Quarkus.run(Quarkus.java:44) at io.quarkus.runtime.Quarkus.run(Quarkus.java:124) at io.quarkus.runner.GeneratedMain.main(Unknown Source) Caused by: java.lang.RuntimeException: Failed to start quarkus at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source) ... 6 more Caused by: java.lang.IllegalArgumentException: Annotation is not a registered qualifier: interface jakarta.enterprise.inject.Any at io.quarkus.arc.impl.Qualifiers.verifyQualifier(Qualifiers.java:152) at io.quarkus.arc.impl.Qualifiers.verify(Qualifiers.java:47) at io.quarkus.arc.impl.ArcContainerImpl.resolveObserverMethods(ArcContainerImpl.java:881) at io.quarkus.arc.impl.EventImpl.createNotifier(EventImpl.java:182) at io.quarkus.arc.impl.ArcContainerImpl.notifierOrNull(ArcContainerImpl.java:513) at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:206) at io.quarkus.arc.Arc.initialize(Arc.java:38) at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:49) at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy_0(Unknown Source) at io.quarkus.deployment.steps.ArcProcessor$initializeContainer1770303700.deploy(Unknown Source) ... 7 more`

This could be reproduced with building the Quarkus app as a native executable using GraalVM.

https://gitlab.com/dlr-shepard/shepard/-/pipelines/1396442562 is the last pipeline with the corresponding state.

Running this build was successful using a simple "Hello Quarkus" example before taking over the codebase in the migration, so it is probably the current implementation that is causing this.

> Attached are the building and integration test CI jobs that produce the failure (A docker image containing GraalVM is used)
>
> undefined
>
> undefined

More details could be found in the linked issue.

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/work_items/106*

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 1, 2024, 09:31 GMT+2:***

added to epic &5

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 1, 2024, 11:06 GMT+2:***

marked this issue as related to #104

**Comment by noheton** [comment]
***In GitLab by @wiglef on May 7, 2025, 15:51 GMT+2:***

@xit-mohamed  is this still relevant? or can we close the issue?
