### ISSUE TITLE
Generated clients fail after switch to SEMVER

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#174]
***In GitLab by @xit-max-hey on Aug 22, 2024, 09:36 GMT+2:***

After merging the MR that introduces switching to SEMVER, the generated python, python-legacy and typescript clients fail to build and upload.

**Job error message for typescript client:**
```
$ cd clients/typescript
$ touch .npmrc
$ echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
$ echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}" >> .npmrc
$ npm install
> @dlr-shepard/shepard-client@-dev.1992 prepare
> npm run build
> @dlr-shepard/shepard-client@-dev.1992 build
> tsc && tsc -p tsconfig.esm.json
added 1 package, and audited 2 packages in 8s
found 0 vulnerabilities
$ npm run build
> @dlr-shepard/shepard-client@-dev.1992 build
> tsc && tsc -p tsconfig.esm.json
$ npm publish --tag ${NPM_TAG}
npm ERR! Invalid version: "-dev.1992"
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-08-22T07_23_10_513Z-debug-0.log
```

**Job error message for python client:**
```
$ cd clients/python
$ python3 setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "/builds/dlr-shepard/shepard/clients/python/setup.py", line 33, in <module>
    setup(
  File "/usr/local/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 146, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 289, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/dist.py", line 325, in _normalize_version
    normalized = str(Version(version))
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/setuptools/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '.dev1992'
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

**Assignees:** xit-max-hey

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/work_items/174*

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 09:47 GMT+2:***

mentioned in commit b6569530090e3ea70342a22373ee50dc992e4a12

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 10:45 GMT+2:***

mentioned in commit 398b00a7f1b2952dcd68b5271618845a6b25c9ac

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 10:47 GMT+2:***

mentioned in commit b30cb456620286924b558e0700b200e034d11707

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 10:56 GMT+2:***

mentioned in commit 0baadc1c8abfaf879bc78252df31688e7b71bcfa

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 11:00 GMT+2:***

mentioned in commit 83dd45074ec8ce2a77500e039314ff10ca52c289

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 11:30 GMT+2:***

mentioned in commit 24c41979541641622625c4b9cebc0e9ed52a62f1

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 11:44 GMT+2:***

mentioned in commit 467eb3239415764f9d2a95d79a00928f53229b75

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 11:56 GMT+2:***

mentioned in commit f3d59eec0a3f4be9957c4c8b05dcae6697d5a777

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 12:08 GMT+2:***

mentioned in commit 33cef186020f0bd42e7deb309d59cd7f637a329b

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 22, 2024, 13:58 GMT+2:***

mentioned in commit 0d011c1f47482097be5ea12b263352821e141a45

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 23, 2024, 09:53 GMT+2:***

mentioned in commit 24d32b1924c650bf5bf6a3ec39febda8c44e2ec2

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 23, 2024, 09:53 GMT+2:***

mentioned in commit fe95ca41d3040d586358eb25f6d5fd2430cc8f39

**Comment by noheton** [comment]
***In GitLab by @xit-max-hey on Aug 23, 2024, 09:53 GMT+2:***

mentioned in commit 2623eeb86e2e72e994652f41f09eb7af045cec5e
