### ISSUE TITLE
Exceptions during first write on timescale timeseries endpoint

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#369]
***In GitLab by @mvistein on Dec 11, 2024, 16:43 GMT+1:***

# Bug Report

## :bug: Summary

Exception during initial write of timeseries data.

## :clipboard: Steps to reproduce

1. An experimental timeseries container is created
2. Payload points are uploaded

## :package: Environment

 
- shepard Version: 2.0.0-dev-4021
- Webbrowser and version:
- shepard client and version: 2.0.0-dev-4021
- Operating system: Linux/Docker

## :bomb: What is the current bug behavior?

During the first write attempt the following exceptions are logged on the client side:

```
14:48:48.400 [-thread-7] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.\nProcess 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.\nProcess 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:48.400 [-thread-9] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.\nProcess 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.\n  Hint: See server log for query details.\n  Where: SQL statement \" ALTER TABLE _timescaledb_internal._hyper_1_2_chunk ADD CONSTRAINT \"2_2_fkog3jr0iowrx3wkun79k0ihs6o\" FOREIGN KEY (timeseries_id) REFERENCES public.timeseries(id) ON DELETE CASCADE \"\nPL/pgSQL function _timescaledb_functions.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 49 at EXECUTE] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:48.400 [-thread-8] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 592 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.\nProcess 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.\nProcess 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 592.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:48.400 [-thread-6] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 586 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.\nProcess 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.\nProcess 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 586.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:49.398 [-thread-4] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 595 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 594.\nProcess 594 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 595.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:49.399 [-thread-3] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 598 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 594.\nProcess 594 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 597.\nProcess 597 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 598.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:49.400 [-thread-2] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 596 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 594.\nProcess 594 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 596.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
14:48:49.401 [-thread-5] ERROR d.d.b.s.s.s.ShepardSink - ApiException in shepard sink cube2: {"status":500,"exception":"OptimisticLockException","message":"org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected\n  Detail: Process 597 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 594.\nProcess 594 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 597.\n  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]"}
```

On the server side the following exceptions are logged:

```
2024-12-11 14:48:48.382 [WARN ] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-18) SQL Error: 0, SQLState: 40P01
2024-12-11 14:48:48.382 [WARN ] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-20) SQL Error: 0, SQLState: 40P01
2024-12-11 14:48:48.382 [WARN ] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-16) SQL Error: 0, SQLState: 40P01
2024-12-11 14:48:48.382 [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-18) ERROR: deadlock detected
  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.
  Hint: See server log for query details.
2024-12-11 14:48:48.383 [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-20) ERROR: deadlock detected
  Detail: Process 586 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 586.
  Hint: See server log for query details.
2024-12-11 14:48:48.383 [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-16) ERROR: deadlock detected
  Detail: Process 592 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 592.
  Hint: See server log for query details.
2024-12-11 14:48:48.388 [WARN ] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-17) SQL Error: 0, SQLState: 40P01
2024-12-11 14:48:48.388 [ERROR] [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-17) ERROR: deadlock detected
  Detail: Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
  Hint: See server log for query details.
  Where: SQL statement " ALTER TABLE _timescaledb_internal._hyper_1_2_chunk ADD CONSTRAINT "2_2_fkog3jr0iowrx3wkun79k0ihs6o" FOREIGN KEY (timeseries_id) REFERENCES public.timeseries(id) ON DELETE CASCADE "
PL/pgSQL function _timescaledb_functions.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 49 at EXECUTE
2024-12-11 14:48:48.391 [ERROR] [de.dlr.shepard.exceptions.ShepardExceptionMapper] (executor-thread-18) org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]: jakarta.persistence.OptimisticLockException: org.hi
bernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]
        at org.hibernate.internal.ExceptionConverterImpl.wrapLockException(ExceptionConverterImpl.java:254)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:100)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:767)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:745)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:146)
        at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:282)
        at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.persist(Unknown Source)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:105)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:111)
        at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:739)
        at de.dlr.shepard.timeseries.repositories.ExperimentalTimeseriesDataPointRepository_ClientProxy.persist(Unknown Source)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService.addDataPointsToTimeseries(ExperimentalTimeseriesService.java:138)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService.saveDataPoints(ExperimentalTimeseriesService.java:99)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService_ClientProxy.saveDataPoints(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest.createExperimentalTimeseries(ExperimentalTimeseriesRest.java:213)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass.createExperimentalTimeseries$$superforward(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
        at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass.createExperimentalTimeseries(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_ClientProxy.createExperimentalTimeseries(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest$quarkusrestinvoker$createExperimentalTimeseries_4fe1f6f65c1dde40aa31ae453022dae0d1cf0afc.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]
        at org.hibernate.dialect.PostgreSQLDialect.lambda$buildSQLExceptionConversionDelegate$1(PostgreSQLDialect.java:1066)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.execute(ResultSetReturnImpl.java:145)
        at org.hibernate.id.insert.InsertReturningDelegate.executeAndExtractReturning(InsertReturningDelegate.java:96)
        at org.hibernate.id.insert.AbstractReturningDelegate.performMutation(AbstractReturningDelegate.java:58)
        at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:47)
        at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:55)
        at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.doStaticInserts(InsertCoordinatorStandard.java:194)
        at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.coordinateInsert(InsertCoordinatorStandard.java:132)
        at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.insert(InsertCoordinatorStandard.java:95)
        at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:85)
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:682)
        at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:293)
        at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:274)
        at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:324)
        at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:393)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:307)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:223)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:136)
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:177)
        at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:95)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:79)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:761)
        ... 45 more
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 593 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 593.
  Hint: See server log for query details.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2733)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2420)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:517)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:434)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:301)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.execute(ResultSetReturnImpl.java:129)
        ... 67 more

2024-12-11 14:48:48.392 [ERROR] [de.dlr.shepard.exceptions.ShepardExceptionMapper] (executor-thread-20) org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 586 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 586.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]: jakarta.persistence.OptimisticLockException: org.hi
bernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 586 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 586.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]
        at org.hibernate.internal.ExceptionConverterImpl.wrapLockException(ExceptionConverterImpl.java:254)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:100)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:767)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:745)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:146)
        at org.hibernate.engine.spi.SessionLazyDelegator.persist(SessionLazyDelegator.java:282)
        at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.persist(Unknown Source)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:105)
        at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:111)
        at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:739)
        at de.dlr.shepard.timeseries.repositories.ExperimentalTimeseriesDataPointRepository_ClientProxy.persist(Unknown Source)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService.addDataPointsToTimeseries(ExperimentalTimeseriesService.java:138)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService.saveDataPoints(ExperimentalTimeseriesService.java:99)
        at de.dlr.shepard.timeseries.services.ExperimentalTimeseriesService_ClientProxy.saveDataPoints(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest.createExperimentalTimeseries(ExperimentalTimeseriesRest.java:213)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass.createExperimentalTimeseries$$superforward(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
        at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:71)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValidationInterceptor.java:21)
        at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_Subclass.createExperimentalTimeseries(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest_ClientProxy.createExperimentalTimeseries(Unknown Source)
        at de.dlr.shepard.timeseries.endpoints.ExperimentalTimeseriesRest$quarkusrestinvoker$createExperimentalTimeseries_4fe1f6f65c1dde40aa31ae453022dae0d1cf0afc.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.hibernate.exception.LockAcquisitionException: could not execute statement [ERROR: deadlock detected
  Detail: Process 586 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 591.
Process 591 waits for ShareRowExclusiveLock on relation 17122 of database 5; blocked by process 594.
Process 594 waits for ShareUpdateExclusiveLock on relation 17131 of database 5; blocked by process 586.
  Hint: See server log for query details.] [insert into timeseries_data_points (boolean_value,double_value,int_value,string_value,time,timeseries_id) values (?,?,?,?,?,?) returning id]
        at org.hibernate.dialect.PostgreSQLDialect.lambda$buildSQLExceptionConversionDelegate$1(PostgreSQLDialect.java:1066)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
...
```

## :notebook: Relevant logs and/or screenshots

```txt
Paste logs here
```

## :thinking_face: Risks & Open Questions

**Assignees:** ZeroOne42

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/work_items/369*

**Comment by noheton** [comment]
also we also must check for potential data loss during initial data upload.

**Comment by noheton** [comment]
***In GitLab by @ZeroOne42 on Jan 8, 2025, 09:29 GMT+1:***

I have written an unit test that calls the TimeseriesService with multiple threads simultaneously. I could not reproduce the Deadlock. I believe the problem is that I use the same instance of TimeseriesService and therefore the same instance of the TimeseriesRepository. I think we have to write a load test to reproduce the deadlock. But I observed the following issue:

There is a problem when the timeseries does not exist and we create it for the first time. This record is only seen by the other threads after the record was committed. That leads to multiple timeseries records with the same values which leads to unexpected behaviour and must be avoid.

I tried to change the isolation level but this does not solve the problem.

From my point of view we have to do the following steps:
1. We need a database constraint to prevent multiple timeseries records stored in db with the same values.
2. We need some kind of atomic upsert (in postgres it is INSERT ... ON CONFLICT)
3. We have to find out if this solves the DEADLOCK problem.

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Jan 8, 2025, 10:10 GMT+1:***

added #395 as child task

**Comment by noheton** [comment]
***In GitLab by @ZeroOne42 on Jan 10, 2025, 16:16 GMT+1:***

We were not able to reproduce exactly the same error as in the logs above but we got also a Deadlock when inserting multiple timeseries records with datapoints. We believe that the underlying problem is the same.

We moved the transaction to the TimeseriesService where the timeseries itself and the corresponding datapoints are stored to database. We also added an unique constraint on the combination of all timeseries fields without the id. That should prevent the system to create duplicate entries for timeseries objects that have the same values. Last but not least we replaced the insert into statement with an insert into ... on conflict statement so that there is no error when trying to insert a duplicate in a concurrency scenario.

@mvistein: Please check the new version in your environment if the problem is really solved. Many thanks.
