### ISSUE TITLE
Fix Neo4J Migrations Error in Standalone Testing

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#87]
***In GitLab by @xit-paul-reinhardt on Jul 31, 2024, 10:41 GMT+2:***

When running the integrations tests in a standalone testrunner in VSCode or Intellij the following error appears:

undefined

<div>

<div>

</div>
</div>

**Assignees:** xit-paul-reinhardt

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/work_items/87*

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Jul 31, 2024, 10:41 GMT+2:***

added #84 as parent issue

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 1, 2024, 14:06 GMT+2:***

I can not reproduce the issue anymore. When I run an integration test using IntelliJ or VSCode I don't get it (doesn't matter if the quarkend is running in parallel or not), when I execute all of them with \`./mvnw verify -P integration\` I don't get the error either (doesn't matter if the quarkend is running in parallel or not). It also doesn't appear in the pipeline.

All in all I would love if somebody could also test this in different scenarios and if we can't reproduce it close this issue.

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 7, 2024, 10:04 GMT+2:***

I had this error when executing `.\mvnw quarkus:dev` after creating new containers and executing the integration tests with `.\mvnw clean verify -DskipUTs`
undefined
Is it related ?

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 8, 2024, 10:36 GMT+2:***

@ZeroOne42 encountered that an instance of quarkus is started during unit testing that may not have the application properties and could potentially emit this error. We will investigate further and may be able to fix this with #78

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 8, 2024, 11:10 GMT+2:***

I don't have the error in the above comment anymore.

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 9, 2024, 17:50 GMT+2:***

This will be resolved in #125 as it was a result of quarkus being started up for unit tests without proper configuration.

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 12, 2024, 13:18 GMT+2:***

Is this related? This happend while starting up the new quarkend with an old database on our dev server

```java
backend-1  | 2024-08-12 11:14:45,568 INFO  [de.dlr.she.end.ServletContextClass] (main) Run database migrations
backend-1  | 2024-08-12 11:14:47,987 ERROR [de.dlr.she.neo.MigrationsRunner] (main) An error occurred during the execution of the migrations: : ac.simons.neo4j.migrations.core.MigrationsException: More migrations have been applied to the database than locally resolved.
backend-1  |    at ac.simons.neo4j.migrations.core.ChainBuilder.buildChain0(ChainBuilder.java:109)
backend-1  |    at ac.simons.neo4j.migrations.core.ChainBuilder.buildChain(ChainBuilder.java:75)
backend-1  |    at ac.simons.neo4j.migrations.core.ChainBuilder.buildChain(ChainBuilder.java:63)
backend-1  |    at ac.simons.neo4j.migrations.core.Migrations.apply0(Migrations.java:711)
backend-1  |    at ac.simons.neo4j.migrations.core.Migrations.lambda$apply$3(Migrations.java:226)
backend-1  |    at ac.simons.neo4j.migrations.core.Migrations.executeWithinLock(Migrations.java:608)
backend-1  |    at ac.simons.neo4j.migrations.core.Migrations.apply(Migrations.java:222)
backend-1  |    at ac.simons.neo4j.migrations.core.Migrations.apply(Migrations.java:204)
backend-1  |    at de.dlr.shepard.neo4j.MigrationsRunner.apply(MigrationsRunner.java:54)
backend-1  |    at de.dlr.shepard.endpoints.ServletContextClass.init(ServletContextClass.java:41)
backend-1  |    at de.dlr.shepard.endpoints.ServletContextClass_ClientProxy.init(Unknown Source)
backend-1  |    at de.dlr.shepard.endpoints.ServletContextClass_Observer_Synthetic_8vaQZ5th-arMWkH0tL83kGFDGYw.notify(Unknown Source)
backend-1  |    at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
backend-1  |    at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
backend-1  |    at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
backend-1  |    at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
backend-1  |    at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
backend-1  |    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
backend-1  |    at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
backend-1  |    at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
backend-1  |    at io.quarkus.runtime.Application.start(Application.java:101)
backend-1  |    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
backend-1  |    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
backend-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
backend-1  |    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
backend-1  |    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
backend-1  | Caused by: java.lang.IndexOutOfBoundsException
backend-1  |    ... 32 more
```

The database reports 6 applied migrations, `Add Versions` is the last one

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 13:41 GMT+2:***

Uh oh, I don't think it's related but we should definitely look into it. I will create a seperate issue in the Backend migration story.
