### ISSUE TITLE
#115 update infrastructure folder - [merged]

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#894]
***In GitLab by @xit-mohamed on Aug 8, 2024, 17:37 GMT+2:***

_Merges #115-Update-infrastructure-folder -> develop_

# Merge Request

## :bomb: Breaking Changes

- There is no more dedicated swagger container, since a Swagger-ui is already provided by the Backend container under `https://backend.your_host/shepard/doc/swagger-ui`.
- Backend log files are now available under `/opt/shepard/backend/logs`.
- There is an additional step in the installation instructions.
- `JAVA_OPTS` is now used instead of `CATALINA_OPTS` as environment variable to adjust available memory in the Backend.

## :goal: Description

Adapt the files under infrastructure/ to use the new Quarkus backend instead.

- `docker-compose.yaml` uses the the same Backend image tag but it now contains the Quarkus backend.
- Removed the Swagger-ui subdomain from `Caddy` config.
- Adjust the `README.md`
- Adapt `index.html`

### :notebook: Checklist

- [x] The code compiles without any warnings.
- [x] I followed the [code review checklist](https://gitlab.com/dlr-shepard/shepard/-/blob/main/CONTRIBUTING.md#code-review-checklist).
- [x] The documentation has been added/updated.

### :link: Related Issues

- Related #
- Closes #

**Approved by:** thaase, xit-paul-reinhardt

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/merge_requests/175*

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 8, 2024, 17:38 GMT+2:***

marked the checklist item **The documentation has been added/updated.** as completed

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 8, 2024, 17:38 GMT+2:***

marked the checklist item **The code compiles without any warnings.** as completed

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 8, 2024, 17:38 GMT+2:***

marked the checklist item **I followed the [code review checklist](https://gitlab.com/dlr-shepard/shepard/-/blob/main/CONTRIBUTING.md#code-review-checklist).** as completed

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 9, 2024, 09:51 GMT+2:***

marked this merge request as **ready**

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @xit-paul-reinhardt on Aug 9, 2024, 10:58 GMT+2:***

Commented on [infrastructure/docker-compose.yml line 12](https://github.com/noheton/shepard/compare/af00116386156e0abce390ede30200457190b13b...3afc4e07e85a15c44806043103a7d9bd7bf63889#diff-f218f6ecb3c684187c2ac12188409e2e5af7f152b399c37e456d78fd7e7d9c10R12)

https://github.com/noheton/shepard/blob/3afc4e07e85a15c44806043103a7d9bd7bf63889/infrastructure/docker-compose.yml#L12



I don't think we need this.

***In GitLab by @xit-mohamed on Aug 12, 2024, 09:53 GMT+2:***

changed this line in [version 2 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089334031&start_sha=3afc4e07e85a15c44806043103a7d9bd7bf63889#a78720d54c8925620742298bb9258589f97186f7_12_12)

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 9, 2024, 10:58 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 9, 2024, 10:59 GMT+2:***

unapproved this merge request

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 12, 2024, 08:02 GMT+2:***

Commented on [infrastructure/docker-compose.yml line 3](https://github.com/noheton/shepard/compare/af00116386156e0abce390ede30200457190b13b...3afc4e07e85a15c44806043103a7d9bd7bf63889#diff-f218f6ecb3c684187c2ac12188409e2e5af7f152b399c37e456d78fd7e7d9c10R3)

https://github.com/noheton/shepard/blob/3afc4e07e85a15c44806043103a7d9bd7bf63889/infrastructure/docker-compose.yml#L3



We should not recommend running dev images. And the quarkend image should be called `backend` now that the old backend is gone.

***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 08:32 GMT+2:***

Yes actually this should still be backend:latest for now, until we migrated the published images to the monorepo.

***In GitLab by @xit-mohamed on Aug 12, 2024, 09:53 GMT+2:***

changed this line in [version 2 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089334031&start_sha=3afc4e07e85a15c44806043103a7d9bd7bf63889#a78720d54c8925620742298bb9258589f97186f7_3_3)

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 12, 2024, 08:19 GMT+2:***

The infrastructure folder seems hard to find for external administrators. We should perhaps add a link to our wiki and README

***In GitLab by @thaase on Aug 12, 2024, 10:07 GMT+2:***

planned in https://gitlab.com/dlr-shepard/shepard/-/issues/144

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 09:53 GMT+2:***

added 1 commit

<ul><li>1bb129e4 - #115 docker compose CR fixes</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089334031&start_sha=3afc4e07e85a15c44806043103a7d9bd7bf63889)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 09:53 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 12, 2024, 10:07 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 10:52 GMT+2:***

Commented on [infrastructure/docker-compose.yml line 20](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...bec8be927e7c5271632936b6e29cae9f4b44b68f#diff-f218f6ecb3c684187c2ac12188409e2e5af7f152b399c37e456d78fd7e7d9c10L20)

https://github.com/noheton/shepard/blob/bec8be927e7c5271632936b6e29cae9f4b44b68f/infrastructure/docker-compose.yml#L20



This needs to be adapted to persist the keys used for api keys. But it's \`/home/jboss/.shepard\` instead of \`/root/.shepard\`

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 11:00 GMT+2:***

mentioned in task #142

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 11:09 GMT+2:***

added 1 commit

<ul><li>4e7a08db - #115 Reenable persistance of shepard api keys</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089431723&start_sha=1bb129e4dea84b7063e1643958de807f7c18fa62)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 11:10 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 11:56 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 12, 2024, 13:04 GMT+2:***

Commented on [infrastructure/.gitignore line 24](https://github.com/noheton/shepard/compare/af00116386156e0abce390ede30200457190b13b...4e7a08db570b1a076d75ffdb6ff14c6d0310d7c2#diff-2cfe3e1ceb805f812736573a76b766c3cb8da0ea0ac4931d15bb75dc566a846aR24)

https://github.com/noheton/shepard/blob/4e7a08db570b1a076d75ffdb6ff14c6d0310d7c2/infrastructure/.gitignore#L22-L24



This is not really necessary, right? According to the docker-compose file logs are stored under `/opt/shepard/backend/logs`

***In GitLab by @xit-mohamed on Aug 12, 2024, 15:17 GMT+2:***

changed this line in [version 4 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089767879&start_sha=4e7a08db570b1a076d75ffdb6ff14c6d0310d7c2#46c214b7936d5098ccb26e77f44dab5277af828d_24_22)

***In GitLab by @xit-mohamed on Aug 12, 2024, 15:19 GMT+2:***

Yes indeed it is not, this and the backend image quarkend tag were testing leftovers, thanks for the catch.

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 12, 2024, 13:07 GMT+2:***

Commented on [infrastructure/docker-compose.yml line 11](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...bec8be927e7c5271632936b6e29cae9f4b44b68f#diff-f218f6ecb3c684187c2ac12188409e2e5af7f152b399c37e456d78fd7e7d9c10L11)

https://github.com/noheton/shepard/blob/bec8be927e7c5271632936b6e29cae9f4b44b68f/infrastructure/docker-compose.yml#L4-L16



Do we have to reorder things? It should be easier for administrators to see changes if we keep the old order

***In GitLab by @xit-mohamed on Aug 12, 2024, 15:14 GMT+2:***

I think the most obvious change here is the mongo variables that are replaced with one connection string. The improvement i can see for the order is to have that variable before or after the variables of INFLUX and NEO4j. Is that what you mean?

***In GitLab by @xit-mohamed on Aug 12, 2024, 15:18 GMT+2:***

Nevermind, now i get what you mean.

***In GitLab by @xit-mohamed on Aug 12, 2024, 15:19 GMT+2:***

Changed it

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 12, 2024, 13:24 GMT+2:***

While migrating our dev server to quarkus I've noticed this error
```java
backend-1  | LogManager error of type OPEN_FAILURE: Failed to set log file
backend-1  | java.io.FileNotFoundException: logs/shepard.log (Permission denied)
backend-1  |    at java.base/java.io.FileOutputStream.open0(Native Method)
backend-1  |    at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
backend-1  |    at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
backend-1  |    at org.jboss.logmanager.handlers.FileHandler.setFile(FileHandler.java:155)
backend-1  |    at org.jboss.logmanager.handlers.PeriodicRotatingFileHandler.setFile(PeriodicRotatingFileHandler.java:113)
backend-1  |    at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.setFileInternal(PeriodicSizeRotatingFileHandler.java:266)
backend-1  |    at org.jboss.logmanager.handlers.PeriodicSizeRotatingFileHandler.setFile(PeriodicSizeRotatingFileHandler.java:174)
backend-1  |    at io.quarkus.runtime.logging.LoggingSetupRecorder.configureFileHandler(LoggingSetupRecorder.java:633)
backend-1  |    at io.quarkus.runtime.logging.LoggingSetupRecorder.initializeLogging(LoggingSetupRecorder.java:174)
backend-1  |    at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy_0(Unknown Source)
backend-1  |    at io.quarkus.deployment.steps.LoggingResourceProcessor$setupLoggingRuntimeInit2024815463.deploy(Unknown Source)
backend-1  |    at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
backend-1  |    at io.quarkus.runtime.Application.start(Application.java:101)
backend-1  |    at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
backend-1  |    at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
backend-1  |    at io.quarkus.runner.GeneratedMain.main(Unknown Source)
backend-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
backend-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
backend-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
backend-1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:569)
backend-1  |    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
backend-1  |    at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
```

This is a result of reusing the old tomcat directory with root permissions for quarkus. We probably cannot fix this, but should atleast document it as a known issue (infrasturcture/README). And we should document how to fix it:

```sh
sudo chown 185:185 /opt/shepard/backend/logs/
```

***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 16:40 GMT+2:***

Fixed in #145

***In GitLab by @thaase on Aug 13, 2024, 08:41 GMT+2:***

no, i don't think so. This is a different one

***In GitLab by @xit-paul-reinhardt on Aug 13, 2024, 09:23 GMT+2:***

Ah right, sorry!

***In GitLab by @xit-paul-reinhardt on Aug 13, 2024, 09:27 GMT+2:***

I think the same will be applicable for the folder with the keys.

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:07 GMT+2:***

Added to README.md

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 15:17 GMT+2:***

added 1 commit

<ul><li>4ff10319 - #115 CR adjustments</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1089767879&start_sha=4e7a08db570b1a076d75ffdb6ff14c6d0310d7c2)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 15:17 GMT+2:***

reset approvals from @xit-paul-reinhardt by pushing to the branch

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 12, 2024, 15:19 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 16:40 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 12, 2024, 16:44 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:01 GMT+2:***

added 8 commits

<ul><li>4ff10319...427c172a - 6 commits from branch <code>develop</code></li><li>9c598118 - Merge branch &#39;develop&#39; into #115-Update-infrastructure-folder</li><li>d30762aa - #115 Add permission issue to README</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090564550&start_sha=4ff10319e4c86ff9f1e83a1c7cf4c68c8c9ed771)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:02 GMT+2:***

reset approvals from @xit-paul-reinhardt by pushing to the branch

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:06 GMT+2:***

added 2 commits

<ul><li>c86ecfbe - Revert &quot;#115 Add permission issue to README&quot;</li><li>3f9eb8a5 - #115 fix formatting</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090570429&start_sha=d30762aac1dc0173b92bb16089c1665755ed26c8)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:07 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 13, 2024, 10:20 GMT+2:***

Commented on [infrastructure/README.md line 232](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...e8c3ec1efa3c169c5816516bc28afa54cfea9a85#diff-d5b352058053e1306240bcd8ab265b3234d611212cd196b2001fbb9131048566R232)

https://github.com/noheton/shepard/blob/e8c3ec1efa3c169c5816516bc28afa54cfea9a85/infrastructure/README.md#L233



I assume that this is always necessary, right? In this case, this would be a mandatory step for the installation. See comment below for a suggestion

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:25 GMT+2:***

I had it in mind but was not very sure, we are stating that this is an issue it felt weird to include it in the steps and say it is a solution to an issue. But since it is actually a mandatory thing to do i think you are right, i will move it up.

***In GitLab by @thaase on Aug 13, 2024, 10:27 GMT+2:***

Maybe have it as a necessary step and as an issue aswell. The issue could point to that step as a solution instead of repeating the same thing

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:34 GMT+2:***

Sounds great!

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:42 GMT+2:***

changed this line in [version 8 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090617206&start_sha=e8c3ec1efa3c169c5816516bc28afa54cfea9a85#885e26bd7a75cc3a472924a0f71ca6cf4bbdcdd2_232_242)

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:46 GMT+2:***

Mentioned as breaking change in the description.

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 13, 2024, 10:24 GMT+2:***

Commented on [infrastructure/README.md line 139](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...3f9eb8a52b776f0c51af5a63d3e118ac3c5a1413#diff-d5b352058053e1306240bcd8ab265b3234d611212cd196b2001fbb9131048566R139)

https://github.com/noheton/shepard/blob/3f9eb8a52b776f0c51af5a63d3e118ac3c5a1413/infrastructure/README.md#L138-Lnull



```suggestion:-1+0
You can find the backend logs in `/opt/shepard/backend/logs`.
```

***In GitLab by @xit-mohamed on Aug 13, 2024, 10:26 GMT+2:***

changed this line in [version 7 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090596324&start_sha=3f9eb8a52b776f0c51af5a63d3e118ac3c5a1413#885e26bd7a75cc3a472924a0f71ca6cf4bbdcdd2_139_138)

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 13, 2024, 10:24 GMT+2:***

Commented on [infrastructure/README.md line 55](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...bec8be927e7c5271632936b6e29cae9f4b44b68f#diff-d5b352058053e1306240bcd8ab265b3234d611212cd196b2001fbb9131048566L55)

https://github.com/noheton/shepard/blob/bec8be927e7c5271632936b6e29cae9f4b44b68f/infrastructure/README.md#L55



e.g. create backend directories and set directory permissions here

```suggestion:-0+0
### 4. Create necessary directories

mkdir ...
chown ...

```

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:26 GMT+2:***

added 1 commit

<ul><li>e8c3ec1e - #115 Fix typo</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090596324&start_sha=3f9eb8a52b776f0c51af5a63d3e118ac3c5a1413)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 10:42 GMT+2:***

added 1 commit

<ul><li>6aad2f75 - #115 Include permissions fix in installation steps</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090617206&start_sha=e8c3ec1efa3c169c5816516bc28afa54cfea9a85)

**Comment by noheton** [comment]
**Discussion in GitLab:**

***In GitLab by @thaase on Aug 13, 2024, 11:05 GMT+2:***

Commented on [infrastructure/README.md line 242](https://github.com/noheton/shepard/compare/427c172a0d48139f36b9a31d587566dde7f9c49e...6aad2f759faf1f2251de925d6e142d41e7111bae#diff-d5b352058053e1306240bcd8ab265b3234d611212cd196b2001fbb9131048566R242)

https://github.com/noheton/shepard/blob/6aad2f759faf1f2251de925d6e142d41e7111bae/infrastructure/README.md#L242



The directories have already been created by docker when this error occurs

```suggestion:-0+0
To keep the backend docker image secure and clean we can keep relying on the same user and make sure to [set the right directory permissions](#4-create-necessary-directories).
```

***In GitLab by @xit-mohamed on Aug 13, 2024, 11:41 GMT+2:***

changed this line in [version 9 of the diff](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090698959&start_sha=6aad2f759faf1f2251de925d6e142d41e7111bae#885e26bd7a75cc3a472924a0f71ca6cf4bbdcdd2_242_242)

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 13, 2024, 11:05 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 13, 2024, 11:05 GMT+2:***

One last comment. The rest looks good :+1:

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 11:41 GMT+2:***

resolved all threads

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 11:41 GMT+2:***

added 1 commit

<ul><li>bec8be92 - #115 Adjust text</li></ul>

[Compare with previous version](/dlr-shepard/shepard/-/merge_requests/175/diffs?diff_id=1090698959&start_sha=6aad2f759faf1f2251de925d6e142d41e7111bae)

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 11:41 GMT+2:***

reset approvals from @thaase by pushing to the branch

**Comment by noheton** [comment]
***In GitLab by @thaase on Aug 13, 2024, 11:43 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
***In GitLab by @xit-paul-reinhardt on Aug 13, 2024, 11:43 GMT+2:***

approved this merge request

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 11:44 GMT+2:***

enabled automatic add to merge train when checks pass

**Comment by noheton** [comment]
***In GitLab by @xit-mohamed on Aug 13, 2024, 11:46 GMT+2:***

started a [merge train](https://gitlab.com/dlr-shepard/shepard/-/merge_trains)
